package com.fpsmod.config;

import com.fpsmod.OogaMod;
import com.fpsmod.io.AtomicFileWriter;
import net.fabricmc.loader.api.FabricLoader;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Writes a player-friendly README.md into {@code config/otters_civ_revived/}
 * every time the mod loads. Plain-English guide to each config file so a
 * server owner who barely touches JSON can still tweak the mod confidently.
 *
 * Always overwrites — the README is generated documentation, not user data.
 */
public final class ConfigReadmeWriter {
    private static final String CONFIG_SUBDIR = "otters_civ_revived";
    private static final String FILE_NAME = "README.md";

    private ConfigReadmeWriter() {}

    public static Path readmePath() {
        return FabricLoader.getInstance().getConfigDir().resolve(CONFIG_SUBDIR).resolve(FILE_NAME);
    }

    public static void writeOrUpdate() {
        Path dir = FabricLoader.getInstance().getConfigDir().resolve(CONFIG_SUBDIR);
        Path path = dir.resolve(FILE_NAME);
        try {
            Files.createDirectories(dir);
            String content = buildReadme();
            AtomicFileWriter.writeAtomically(path, w -> w.write(content));
            OogaMod.LOGGER.info("[otters_civ_revived] Wrote config README at {}", path);
        } catch (IOException e) {
            OogaMod.LOGGER.error("[otters_civ_revived] Failed to write config README", e);
        }
    }

    private static String buildReadme() {
        return String.join("\n",
            "# Otters Civ. Revived — Config Guide",
            "",
            "Hi! This folder is where the **Otters Civ. Revived** mod (a.k.a. Project OOGA)",
            "stores its settings. Every file in here is a plain text file you can open with",
            "Notepad, TextEdit, VS Code, or any text editor.",
            "",
            "**Don't panic.** You do *not* have to touch any of these files for the mod to work.",
            "The mod creates them with sensible defaults the first time it loads. Only edit them",
            "if you want to change how things behave on your server.",
            "",
            "---",
            "",
            "## Before you edit anything",
            "",
            "1. **Stop the server first.** Edits made while the server is running may be ignored",
            "   or overwritten when the server shuts down.",
            "2. **Make a backup.** Just copy the file and rename the copy to e.g.",
            "   `economy.json.backup`. If you mess something up, rename it back.",
            "3. **JSON is picky.** Watch for these:",
            "   - Strings go in `\"double quotes\"`.",
            "   - Numbers do NOT use quotes. `100` is correct, `\"100\"` is wrong.",
            "   - `true` and `false` are lowercase, no quotes.",
            "   - Every item in a list/object except the last one needs a comma after it.",
            "   - If the mod refuses to load a file, it will fall back to defaults and write",
            "     an error in the server log (`logs/latest.log`). Open that log to see what line broke.",
            "4. **Online JSON validators** (e.g. https://jsonlint.com) can paste-check your file",
            "   before you save it back.",
            "",
            "---",
            "",
            "## The files in this folder",
            "",
            "| File | What it controls |",
            "|---|---|",
            "| `economy.json` | Money — currency name, starting balance, `/pay` rules. |",
            "| `jobs.json` | The 5 jobs (Miner, Lumberjack, Farmer, Excavator, Fighter), how much XP and money they give. |",
            "| `guilds.json` | Guild limits, claim costs, PvP & block protection. |",
            "| `rewards.json` | Which blocks/mobs pay coins when broken/killed, how often. |",
            "| `block_values.json` | Per-block coin payouts. Auto-filled from tags on first run. |",
            "| `entity_values.json` | Per-mob coin payouts. Auto-filled from tags on first run. |",
            "| `README.md` | This file. Auto-rewritten every time the mod loads. |",
            "",
            "---",
            "",
            "## `economy.json` — Money settings",
            "",
            "Controls coins, the `/pay` command, and the welcome message.",
            "",
            "| Setting | Meaning | Default |",
            "|---|---|---|",
            "| `currencySymbol` | The character shown before money amounts in chat. | `\"$\"` |",
            "| `currencyName` | What you call ONE coin. | `\"coin\"` |",
            "| `currencyNamePlural` | What you call MANY coins. | `\"coins\"` |",
            "| `newPlayerStartingBalance` | Coins given to a player the first time they join. `0` = nothing. | `0` |",
            "| `maxBalance` | Hard cap on a player's wallet. `0` = no cap. | `0` |",
            "| `maxTransferPerCommand` | Most coins one `/pay` can move. `0` = no cap. | `100000` |",
            "| `minTransferAmount` | Smallest amount `/pay` will allow. Stops 1-coin spam. | `1` |",
            "| `transferCooldownSeconds` | Seconds the sender must wait between `/pay`s. `0` = no cooldown. | `3` |",
            "| `transferFlatFee` | Extra coins burned from the sender on each `/pay`. `0` = free. | `0` |",
            "| `allowSelfPay` | Can a player `/pay` themselves? Almost always `false`. | `false` |",
            "| `showJoinWelcome` | Show the welcome chat message on first join? | `true` |",
            "",
            "**Example tweak — call your money \"Gold\" with a `G` symbol:**",
            "```json",
            "\"currencySymbol\": \"G\",",
            "\"currencyName\": \"gold piece\",",
            "\"currencyNamePlural\": \"gold pieces\"",
            "```",
            "",
            "---",
            "",
            "## `jobs.json` — Jobs, XP, and level bonuses",
            "",
            "Two big sections:",
            "",
            "- `global` — rules that apply to every job.",
            "- `jobs` — the list of jobs themselves.",
            "",
            "### `global` settings",
            "",
            "| Setting | Meaning | Default |",
            "|---|---|---|",
            "| `enabled` | Master switch for the whole jobs system. | `true` |",
            "| `activationPolicy` | `\"single\"` = a player can have ONE job at a time. `\"multi\"` = several. | `\"single\"` |",
            "| `maxActiveJobs` | If `multi`, how many jobs at once. Ignored when `single`. | `1` |",
            "| `defaultIconGlyph` | Fallback symbol shown for a job with no icon. | `\"*\"` |",
            "| `antiAbuseEnabled` | Anti-grind: dial down rewards if a player spams the same job. | `true` |",
            "| `antiAbuseWindowSeconds` | How wide the anti-grind window is. | `60` |",
            "| `antiAbuseSoftCap` | Events per window allowed at FULL reward. Past this, payout ramps down. | `60` |",
            "| `antiAbuseHardCap` | Events per window where reward hits the floor. | `240` |",
            "| `antiAbuseFloor` | Lowest payout multiplier (`0.1` = 10%). | `0.1` |",
            "| `persistEveryNEvents` | Save jobs to disk every N events (0 = save every event). | `25` |",
            "",
            "### Each entry in `jobs`",
            "",
            "| Field | What it does |",
            "|---|---|",
            "| `id` | Internal name (lowercase, no spaces). Used by `/job join <id>`. |",
            "| `displayName` | The name players see in the UI. |",
            "| `description` | One-line blurb shown in `/job` UI. |",
            "| `enabled` | Set to `false` to hide a job entirely. |",
            "| `joinable` | Set to `false` to keep a job visible but un-joinable. |",
            "| `iconGlyph` | A single symbol/emoji shown next to the name. |",
            "| `triggers` | What ACTIONS earn XP and coin (e.g. break a block in this tag, kill a mob in this tag). |",
            "| `progression.maxLevel` | Highest level a player can reach in this job. |",
            "| `progression.xpPerEvent` | XP gained from each rewarded action. |",
            "| `progression.xpBase` / `xpExponent` | Math curve for level-up cost. Bigger numbers = slower leveling. |",
            "| `boosts.moneyMultiplierByLevel` | List of `{level, value}` — at that level, payouts are multiplied. `1.10` = +10%. |",
            "| `boosts.moneyFlatBonusByLevel` | Flat extra coins added per payout once that level is reached. |",
            "| `boosts.xpMultiplierByLevel` | Same idea but applied to XP gain. |",
            "",
            "**Quick tweaks:**",
            "- Want faster leveling? Raise `xpPerEvent`, e.g. from `5` to `10`.",
            "- Want to disable Fighter? Find its block and set `\"enabled\": false`.",
            "- Want bigger payouts at level 40? Edit the last entry in `moneyMultiplierByLevel`.",
            "",
            "---",
            "",
            "## `guilds.json` — Guild rules and protection",
            "",
            "Controls everything about guilds — how big they are, what claiming costs, who can build where.",
            "",
            "| Setting | Meaning | Default |",
            "|---|---|---|",
            "| `enabled` | Master switch for the whole guild system. | `true` |",
            "| `maxMembers` | Member cap per guild. | `20` |",
            "| `maxOfficers` | Officer cap per guild. | `4` |",
            "| `maxClaims` | How many chunks a guild can claim. | `16` |",
            "| `claimCost` | Coins charged for each chunk claim. | `100` |",
            "| `creationCost` | Coins charged to FOUND a new guild. | `250` |",
            "| `minNameLength` / `maxNameLength` | Allowed length of a guild name. | `3` / `24` |",
            "| `disbandRefundClaims` | Refund claim costs when a guild disbands? | `true` |",
            "| `allowOpenGuilds` | Can guilds be set to free-join (no invite needed)? | `true` |",
            "| `homeTeleportCooldownSeconds` | Wait between `/guild home` uses. | `60` |",
            "| `protectBlocks` | Block-break/place blocked for non-members in claims? | `true` |",
            "| `protectContainers` | Chests/furnaces locked to non-members in claims? | `true` |",
            "| `protectInteractables` | Doors/buttons/levers locked to non-members? | `false` |",
            "| `allowMemberBuild` | Regular members allowed to build in claims? | `true` |",
            "| `allowOfficerBuild` | Officers allowed to build in claims? | `true` |",
            "| `pvpInClaims` | Allow PvP inside claimed chunks? | `true` |",
            "| `showChunkBorders` | Show the chunk-border overlay client-side. | `true` |",
            "| `mapRadius` | Chunk radius shown on the guild map. | `4` |",
            "| `overlayDurationSeconds` | How long the chunk-border overlay stays on screen. | `30` |",
            "",
            "**Want a peaceful, no-PvP server?** Set `\"pvpInClaims\": false`.",
            "",
            "**Want claiming to be free?** Set `\"claimCost\": 0` and `\"creationCost\": 0`.",
            "",
            "---",
            "",
            "## `rewards.json` — What pays out coins",
            "",
            "Controls the \"break a block / kill a mob → get coins\" loop.",
            "",
            "| Setting | Meaning | Default |",
            "|---|---|---|",
            "| `enabled` | Master switch. `false` = no money from breaking/killing. | `true` |",
            "| `blockTag` | The Minecraft tag of blocks that pay out by default. | `otters_civ_revived:currency_blocks` |",
            "| `blockReward` | Default coins per rewarded block. | `1` |",
            "| `entityTag` | Tag of mobs that pay on kill. | `otters_civ_revived:currency_mobs` |",
            "| `entityReward` | Default coins per rewarded kill. | `5` |",
            "| `blockCooldownMs` | Anti-spam: ms between rewarded breaks (per player). | `50` |",
            "| `entityCooldownMs` | Anti-spam: ms between rewarded kills (per player). | `100` |",
            "| `skipCreative` | Skip payouts in Creative mode? | `true` |",
            "| `skipSpectator` | Skip payouts in Spectator? | `true` |",
            "| `announceRewards` | Send the small \"+5 coins\" chat message? | `true` |",
            "| `dimensionBlacklist` | List of dimension IDs where payouts are OFF. e.g. `[\"minecraft:the_nether\"]`. | `[]` |",
            "| `blockRewards` | Per-block overrides. Wins over the tag default. See below. | `{}` |",
            "| `entityRewards` | Per-mob overrides. Same idea. | `{}` |",
            "",
            "### How the per-block / per-mob payouts work",
            "",
            "On the FIRST server boot after install, the mod auto-creates two helper files:",
            "",
            "- `block_values.json` — every block in the currency tag, with its coin value.",
            "- `entity_values.json` — every mob in the currency tag, with its coin value.",
            "",
            "These look like:",
            "```json",
            "{",
            "  \"minecraft:coal_ore\": 1,",
            "  \"minecraft:diamond_ore\": 25,",
            "  \"minecraft:iron_ore\": 5",
            "}",
            "```",
            "",
            "**Edit those files to change individual payouts** without touching tags. Numbers must be",
            "whole numbers ≥ 0. Set a value to `0` to make a block/mob explicitly pay nothing.",
            "",
            "Precedence (lowest → highest priority):",
            "1. Tag default (`blockReward` / `entityReward`).",
            "2. Inline `blockRewards` / `entityRewards` in `rewards.json`.",
            "3. The sibling file (`block_values.json` / `entity_values.json`).",
            "",
            "So a value in `block_values.json` will always win.",
            "",
            "---",
            "",
            "## I broke something. Now what?",
            "",
            "1. Stop the server.",
            "2. Delete the file you edited (e.g. `economy.json`).",
            "3. Restart. The mod will write a fresh defaults file.",
            "4. Or restore your `.backup` copy if you made one.",
            "",
            "If a file fails to load, the mod uses defaults for THIS session and logs the error to",
            "`logs/latest.log`. The bad file is left untouched on disk so you can fix it.",
            "",
            "---",
            "",
            "## Useful in-game commands",
            "",
            "- `/money` — check your wallet.",
            "- `/pay <player> <amount>` — send coins.",
            "- `/job list`, `/job join <id>`, `/job leave <id>` — manage your job.",
            "- `/guild create <name>`, `/guild claim`, `/guild home` — guild basics.",
            "- `/otter` and `/ooga` — mod info, reload, diagnostics (op-only).",
            "",
            "---",
            "",
            "*This README is regenerated every time the mod loads, so don't bother editing it —",
            "your changes will be wiped. Edit the `.json` files instead.*",
            ""
        );
    }
}
